### ISSUE TITLE
Corrección de información 

### ISSUE THREAD

**Issue by ankris812** [g4spin/FlipperZero#1]
Todos los custom firmware permiten seleccionar el teclado en otros idiomas. Sólo tienes que copiarlos a la sd. No solo roguemaster.  El único firmware que no lo permite es el original

**Comment by g4spin** [comment]
Gracias ankris812 por la información. La verdad que llevo muy poco con el y ando probando cosas.

**Comment by ankris812** [comment]
Nada, nada. Cualquier cosa me mencionas acá y te digo.
